In [1]:
import numpy as np

In [3]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [4]:
array2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(array2.shape)

(15,)


In [5]:
a = array2.reshape(3,5) 
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
print("shape: ",a.shape)
print("dimension: ",a.ndim)
print("data type: ",a.dtype.name) 
print("size: ",a.size)         
print("type",type(a))

shape:  (3, 5)
dimension:  2
data type:  int64
size:  15
type <class 'numpy.ndarray'>


In [7]:
array3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
print(array3.shape)

(3, 4)


In [10]:
zeros= np.zeros((3,4))

In [11]:
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty((4,5))

array([[4.66221951e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [14]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
a= np.linspace(0,10,20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [16]:
a= np.array([1,2,3])
b= np.array([4,5,6]) 

print(a+b)
print(a-b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [17]:
a= np.array([1,2,3,4,5,6,7])

In [18]:
liste = [1,2,3,4]

array = np.array([5,6,7,8])

print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [19]:
array = np.array(liste)
print(array)

[1 2 3 4]


In [20]:
liste2 = list(array)
print(liste2)

[1, 2, 3, 4]


In [21]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [22]:
b=a
c=a
b[0]=5 
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [23]:
d = a.copy()

In [24]:
a= np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [25]:
print(a[0])

1


In [26]:
print(a[0:4])

[1 2 3 4]


In [27]:
reverse_array = a[::-1]
print(reverse_array)

[7 6 5 4 3 2 1]


In [28]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
print(b[1,1])

print(b[:,1])

print(b[1,:])

print(b[1,1:4])

print(b[-1,:])

print(b[:,-1])

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [30]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
a = array.ravel()
print(a)

[1 2 3 4 5 6 7 8 9]


In [32]:
array2 = a.reshape(3,3)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
array_transpose = array2.T
print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
array3 = np.array([[1,2],[3,4],[5,6]])
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [35]:
array3.resize((2,3))
print(array3)

[[1 2 3]
 [4 5 6]]
